
services:
  ml-service-green:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iris-ml-green
    ports:
      - "8082:8080"
    environment:
      - MODEL_VERSION=v1.1.0
    volumes:
      - ./app/iris_classifier_v2.pkl:/app/iris_classifier_pipeline.pkl
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
